/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct AssemblyProcessorRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.AssemblyProcessor;

		public int Index;
		public UInt32 Processor;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct AssemblyProcessorRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal AssemblyProcessorRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator AssemblyProcessorRowIndex(RowIndex rowIndex) {
			return new AssemblyProcessorRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(AssemblyProcessorRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class AssemblyProcessorRowFactory : RowFactory<AssemblyProcessorRow> {

		public AssemblyProcessorRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return AssemblyProcessorRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ 4
				;
		}

		public override AssemblyProcessorRow Parse(byte[] buf, ref int position) {
			AssemblyProcessorRow value;
			value.Index = 0;
			value.Processor = Heap.ReadUInt32(buf, ref position);
			return value;
		}

	}

}
