/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct AssemblyRefProcessorRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.AssemblyRefProcessor;

		public int Index;
		public UInt32 Processor;
		public AssemblyRefRowIndex AssemblyRef;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct AssemblyRefProcessorRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal AssemblyRefProcessorRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator AssemblyRefProcessorRowIndex(RowIndex rowIndex) {
			return new AssemblyRefProcessorRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(AssemblyRefProcessorRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class AssemblyRefProcessorRowFactory : RowFactory<AssemblyRefProcessorRow> {

		public AssemblyRefProcessorRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return AssemblyRefProcessorRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ 4
				+ Heap.GetPhysicalSizeOfIndex(AssemblyRefRow.TableId)
				;
		}

		public override AssemblyRefProcessorRow Parse(byte[] buf, ref int position) {
			AssemblyRefProcessorRow value;
			value.Index = 0;
			value.Processor = Heap.ReadUInt32(buf, ref position);
			value.AssemblyRef = (AssemblyRefRowIndex)Heap.ReadRowIndex(AssemblyRefRow.TableId, buf, ref position);
			return value;
		}

	}

}
