/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct AssemblyRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.Assembly;

		public int Index;
		public UInt32 HashAlgId;
		public UInt16 MajorVersion;
		public UInt16 MinorVersion;
		public UInt16 BuildNumber;
		public UInt16 RevisionNumber;
		public AssemblyFlags Flags;
		public BlobHeapIndex PublicKey;
		public StringHeapIndex Name;
		public StringHeapIndex Culture;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct AssemblyRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal AssemblyRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator AssemblyRowIndex(RowIndex rowIndex) {
			return new AssemblyRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(AssemblyRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class AssemblyRowFactory : RowFactory<AssemblyRow> {

		public AssemblyRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return AssemblyRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ 4
				+ 2
				+ 2
				+ 2
				+ 2
				+ 4
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.Blob)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.String)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.String)
				;
		}

		public override AssemblyRow Parse(byte[] buf, ref int position) {
			AssemblyRow value;
			value.Index = 0;
			value.HashAlgId = Heap.ReadUInt32(buf, ref position);
			value.MajorVersion = Heap.ReadUInt16(buf, ref position);
			value.MinorVersion = Heap.ReadUInt16(buf, ref position);
			value.BuildNumber = Heap.ReadUInt16(buf, ref position);
			value.RevisionNumber = Heap.ReadUInt16(buf, ref position);
			value.Flags = (AssemblyFlags)Heap.ReadEnum32(buf, ref position);
			value.PublicKey = Heap.ReadBlobHeapIndex(buf, ref position);
			value.Name = Heap.ReadStringHeapIndex(buf, ref position);
			value.Culture = Heap.ReadStringHeapIndex(buf, ref position);
			return value;
		}

	}

}
