/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct ConstantRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.Constant;

		public int Index;
		public Byte Type;
		public HasConstantCodedIndex Parent;
		public BlobHeapIndex Value;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct ConstantRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal ConstantRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator ConstantRowIndex(RowIndex rowIndex) {
			return new ConstantRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(ConstantRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class ConstantRowFactory : RowFactory<ConstantRow> {

		public ConstantRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return ConstantRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ 1
				+ Heap.GetPhysicalSizeOfIndex(CodedIndexes.HasConstant)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.Blob)
				;
		}

		public override ConstantRow Parse(byte[] buf, ref int position) {
			ConstantRow value;
			value.Index = 0;
			value.Type = Heap.ReadByte(buf, ref position);
			value.Parent = (HasConstantCodedIndex)Heap.ReadCodedIndex(CodedIndexes.HasConstant, buf, ref position);
			value.Value = Heap.ReadBlobHeapIndex(buf, ref position);
			return value;
		}

	}

}
