/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct CustomAttributeRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.CustomAttribute;

		public int Index;
		public HasCustomAttributeCodedIndex Parent;
		public CustomAttributeTypeCodedIndex Type;
		public BlobHeapIndex Value;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct CustomAttributeRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal CustomAttributeRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator CustomAttributeRowIndex(RowIndex rowIndex) {
			return new CustomAttributeRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(CustomAttributeRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class CustomAttributeRowFactory : RowFactory<CustomAttributeRow> {

		public CustomAttributeRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return CustomAttributeRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ Heap.GetPhysicalSizeOfIndex(CodedIndexes.HasCustomAttribute)
				+ Heap.GetPhysicalSizeOfIndex(CodedIndexes.CustomAttributeType)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.Blob)
				;
		}

		public override CustomAttributeRow Parse(byte[] buf, ref int position) {
			CustomAttributeRow value;
			value.Index = 0;
			value.Parent = (HasCustomAttributeCodedIndex)Heap.ReadCodedIndex(CodedIndexes.HasCustomAttribute, buf, ref position);
			value.Type = (CustomAttributeTypeCodedIndex)Heap.ReadCodedIndex(CodedIndexes.CustomAttributeType, buf, ref position);
			value.Value = Heap.ReadBlobHeapIndex(buf, ref position);
			return value;
		}

	}

}
