/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct DeclSecurityRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.DeclSecurity;

		public int Index;
		public UInt16 Action;
		public HasDeclSecurityCodedIndex Parent;
		public BlobHeapIndex PermissionSet;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct DeclSecurityRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal DeclSecurityRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator DeclSecurityRowIndex(RowIndex rowIndex) {
			return new DeclSecurityRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(DeclSecurityRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class DeclSecurityRowFactory : RowFactory<DeclSecurityRow> {

		public DeclSecurityRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return DeclSecurityRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ 2
				+ Heap.GetPhysicalSizeOfIndex(CodedIndexes.HasDeclSecurity)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.Blob)
				;
		}

		public override DeclSecurityRow Parse(byte[] buf, ref int position) {
			DeclSecurityRow value;
			value.Index = 0;
			value.Action = Heap.ReadUInt16(buf, ref position);
			value.Parent = (HasDeclSecurityCodedIndex)Heap.ReadCodedIndex(CodedIndexes.HasDeclSecurity, buf, ref position);
			value.PermissionSet = Heap.ReadBlobHeapIndex(buf, ref position);
			return value;
		}

	}

}
