/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct EventRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.Event;

		public int Index;
		public EventAttributes EventFlags;
		public StringHeapIndex Name;
		public TypeDefOrRefCodedIndex EventType;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct EventRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal EventRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator EventRowIndex(RowIndex rowIndex) {
			return new EventRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(EventRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class EventRowFactory : RowFactory<EventRow> {

		public EventRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return EventRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ 2
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.String)
				+ Heap.GetPhysicalSizeOfIndex(CodedIndexes.TypeDefOrRef)
				;
		}

		public override EventRow Parse(byte[] buf, ref int position) {
			EventRow value;
			value.Index = 0;
			value.EventFlags = (EventAttributes)Heap.ReadEnum16(buf, ref position);
			value.Name = Heap.ReadStringHeapIndex(buf, ref position);
			value.EventType = (TypeDefOrRefCodedIndex)Heap.ReadCodedIndex(CodedIndexes.TypeDefOrRef, buf, ref position);
			return value;
		}

	}

}
