/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct ExportedTypeRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.ExportedType;

		public int Index;
		public TypeAttributes Flags;
		public TypeDefRowIndex TypeDefId;
		public StringHeapIndex TypeName;
		public StringHeapIndex TypeNamespace;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct ExportedTypeRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal ExportedTypeRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator ExportedTypeRowIndex(RowIndex rowIndex) {
			return new ExportedTypeRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(ExportedTypeRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class ExportedTypeRowFactory : RowFactory<ExportedTypeRow> {

		public ExportedTypeRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return ExportedTypeRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ 4
				+ Heap.GetPhysicalSizeOfIndex(TypeDefRow.TableId)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.String)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.String)
				;
		}

		public override ExportedTypeRow Parse(byte[] buf, ref int position) {
			ExportedTypeRow value;
			value.Index = 0;
			value.Flags = (TypeAttributes)Heap.ReadEnum32(buf, ref position);
			value.TypeDefId = (TypeDefRowIndex)Heap.ReadRowIndex(TypeDefRow.TableId, buf, ref position);
			value.TypeName = Heap.ReadStringHeapIndex(buf, ref position);
			value.TypeNamespace = Heap.ReadStringHeapIndex(buf, ref position);
			return value;
		}

	}

}
