/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct FieldMarshalRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.FieldMarshal;

		public int Index;
		public HasFieldMarshalCodedIndex Parent;
		public BlobHeapIndex NativeType;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct FieldMarshalRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal FieldMarshalRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator FieldMarshalRowIndex(RowIndex rowIndex) {
			return new FieldMarshalRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(FieldMarshalRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class FieldMarshalRowFactory : RowFactory<FieldMarshalRow> {

		public FieldMarshalRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return FieldMarshalRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ Heap.GetPhysicalSizeOfIndex(CodedIndexes.HasFieldMarshal)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.Blob)
				;
		}

		public override FieldMarshalRow Parse(byte[] buf, ref int position) {
			FieldMarshalRow value;
			value.Index = 0;
			value.Parent = (HasFieldMarshalCodedIndex)Heap.ReadCodedIndex(CodedIndexes.HasFieldMarshal, buf, ref position);
			value.NativeType = Heap.ReadBlobHeapIndex(buf, ref position);
			return value;
		}

	}

}
