/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct FieldRVARow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.FieldRVA;

		public int Index;
		public UInt32 RVA;
		public FieldRowIndex Field;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct FieldRVARowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal FieldRVARowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator FieldRVARowIndex(RowIndex rowIndex) {
			return new FieldRVARowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(FieldRVARowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class FieldRVARowFactory : RowFactory<FieldRVARow> {

		public FieldRVARowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return FieldRVARow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ 4
				+ Heap.GetPhysicalSizeOfIndex(FieldRow.TableId)
				;
		}

		public override FieldRVARow Parse(byte[] buf, ref int position) {
			FieldRVARow value;
			value.Index = 0;
			value.RVA = Heap.ReadUInt32(buf, ref position);
			value.Field = (FieldRowIndex)Heap.ReadRowIndex(FieldRow.TableId, buf, ref position);
			return value;
		}

	}

}
