/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct FileRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.File;

		public int Index;
		public FileAttributes Flags;
		public StringHeapIndex Name;
		public BlobHeapIndex HashValue;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct FileRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal FileRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator FileRowIndex(RowIndex rowIndex) {
			return new FileRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(FileRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class FileRowFactory : RowFactory<FileRow> {

		public FileRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return FileRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ 4
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.String)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.Blob)
				;
		}

		public override FileRow Parse(byte[] buf, ref int position) {
			FileRow value;
			value.Index = 0;
			value.Flags = (FileAttributes)Heap.ReadEnum32(buf, ref position);
			value.Name = Heap.ReadStringHeapIndex(buf, ref position);
			value.HashValue = Heap.ReadBlobHeapIndex(buf, ref position);
			return value;
		}

	}

}
