/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct GenericParamRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.GenericParam;

		public int Index;
		public UInt16 Number;
		public GenericParamAttributes Flags;
		public TypeOrMethodDefCodedIndex Owner;
		public StringHeapIndex Name;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct GenericParamRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal GenericParamRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator GenericParamRowIndex(RowIndex rowIndex) {
			return new GenericParamRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(GenericParamRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class GenericParamRowFactory : RowFactory<GenericParamRow> {

		public GenericParamRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return GenericParamRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ 2
				+ 2
				+ Heap.GetPhysicalSizeOfIndex(CodedIndexes.TypeOrMethodDef)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.String)
				;
		}

		public override GenericParamRow Parse(byte[] buf, ref int position) {
			GenericParamRow value;
			value.Index = 0;
			value.Number = Heap.ReadUInt16(buf, ref position);
			value.Flags = (GenericParamAttributes)Heap.ReadEnum16(buf, ref position);
			value.Owner = (TypeOrMethodDefCodedIndex)Heap.ReadCodedIndex(CodedIndexes.TypeOrMethodDef, buf, ref position);
			value.Name = Heap.ReadStringHeapIndex(buf, ref position);
			return value;
		}

	}

}
