/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct GenericParamConstraintRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.GenericParamConstraint;

		public int Index;
		public GenericParamRowIndex Owner;
		public TypeDefOrRefCodedIndex Constraint;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct GenericParamConstraintRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal GenericParamConstraintRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator GenericParamConstraintRowIndex(RowIndex rowIndex) {
			return new GenericParamConstraintRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(GenericParamConstraintRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class GenericParamConstraintRowFactory : RowFactory<GenericParamConstraintRow> {

		public GenericParamConstraintRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return GenericParamConstraintRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ Heap.GetPhysicalSizeOfIndex(GenericParamRow.TableId)
				+ Heap.GetPhysicalSizeOfIndex(CodedIndexes.TypeDefOrRef)
				;
		}

		public override GenericParamConstraintRow Parse(byte[] buf, ref int position) {
			GenericParamConstraintRow value;
			value.Index = 0;
			value.Owner = (GenericParamRowIndex)Heap.ReadRowIndex(GenericParamRow.TableId, buf, ref position);
			value.Constraint = (TypeDefOrRefCodedIndex)Heap.ReadCodedIndex(CodedIndexes.TypeDefOrRef, buf, ref position);
			return value;
		}

	}

}
