/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct InterfaceImplRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.InterfaceImpl;

		public int Index;
		public TypeDefRowIndex Class;
		public TypeDefOrRefCodedIndex Interface;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct InterfaceImplRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal InterfaceImplRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator InterfaceImplRowIndex(RowIndex rowIndex) {
			return new InterfaceImplRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(InterfaceImplRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class InterfaceImplRowFactory : RowFactory<InterfaceImplRow> {

		public InterfaceImplRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return InterfaceImplRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ Heap.GetPhysicalSizeOfIndex(TypeDefRow.TableId)
				+ Heap.GetPhysicalSizeOfIndex(CodedIndexes.TypeDefOrRef)
				;
		}

		public override InterfaceImplRow Parse(byte[] buf, ref int position) {
			InterfaceImplRow value;
			value.Index = 0;
			value.Class = (TypeDefRowIndex)Heap.ReadRowIndex(TypeDefRow.TableId, buf, ref position);
			value.Interface = (TypeDefOrRefCodedIndex)Heap.ReadCodedIndex(CodedIndexes.TypeDefOrRef, buf, ref position);
			return value;
		}

	}

}
