/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct MethodImplRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.MethodImpl;

		public int Index;
		public TypeDefRowIndex Class;
		public MethodDefOrRefCodedIndex MethodBody;
		public MethodDefOrRefCodedIndex MethodDeclaration;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct MethodImplRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal MethodImplRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator MethodImplRowIndex(RowIndex rowIndex) {
			return new MethodImplRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(MethodImplRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class MethodImplRowFactory : RowFactory<MethodImplRow> {

		public MethodImplRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return MethodImplRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ Heap.GetPhysicalSizeOfIndex(TypeDefRow.TableId)
				+ Heap.GetPhysicalSizeOfIndex(CodedIndexes.MethodDefOrRef)
				+ Heap.GetPhysicalSizeOfIndex(CodedIndexes.MethodDefOrRef)
				;
		}

		public override MethodImplRow Parse(byte[] buf, ref int position) {
			MethodImplRow value;
			value.Index = 0;
			value.Class = (TypeDefRowIndex)Heap.ReadRowIndex(TypeDefRow.TableId, buf, ref position);
			value.MethodBody = (MethodDefOrRefCodedIndex)Heap.ReadCodedIndex(CodedIndexes.MethodDefOrRef, buf, ref position);
			value.MethodDeclaration = (MethodDefOrRefCodedIndex)Heap.ReadCodedIndex(CodedIndexes.MethodDefOrRef, buf, ref position);
			return value;
		}

	}

}
