/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct MethodDefRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.MethodDef;

		public int Index;
		public UInt32 RVA;
		public MethodImplAttributes ImplFlags;
		public MethodAttributes Flags;
		public StringHeapIndex Name;
		public BlobHeapIndex Signature;
		public ParamRowIndex ParamList;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct MethodDefRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal MethodDefRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator MethodDefRowIndex(RowIndex rowIndex) {
			return new MethodDefRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(MethodDefRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class MethodDefRowFactory : RowFactory<MethodDefRow> {

		public MethodDefRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return MethodDefRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ 4
				+ 2
				+ 2
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.String)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.Blob)
				+ Heap.GetPhysicalSizeOfIndex(ParamRow.TableId)
				;
		}

		public override MethodDefRow Parse(byte[] buf, ref int position) {
			MethodDefRow value;
			value.Index = 0;
			value.RVA = Heap.ReadUInt32(buf, ref position);
			value.ImplFlags = (MethodImplAttributes)Heap.ReadEnum16(buf, ref position);
			value.Flags = (MethodAttributes)Heap.ReadEnum16(buf, ref position);
			value.Name = Heap.ReadStringHeapIndex(buf, ref position);
			value.Signature = Heap.ReadBlobHeapIndex(buf, ref position);
			value.ParamList = (ParamRowIndex)Heap.ReadRowIndex(ParamRow.TableId, buf, ref position);
			return value;
		}

	}

}
