/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct MethodSpecRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.MethodSpec;

		public int Index;
		public MethodDefOrRefCodedIndex Method;
		public BlobHeapIndex Instantiation;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct MethodSpecRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal MethodSpecRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator MethodSpecRowIndex(RowIndex rowIndex) {
			return new MethodSpecRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(MethodSpecRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class MethodSpecRowFactory : RowFactory<MethodSpecRow> {

		public MethodSpecRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return MethodSpecRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ Heap.GetPhysicalSizeOfIndex(CodedIndexes.MethodDefOrRef)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.Blob)
				;
		}

		public override MethodSpecRow Parse(byte[] buf, ref int position) {
			MethodSpecRow value;
			value.Index = 0;
			value.Method = (MethodDefOrRefCodedIndex)Heap.ReadCodedIndex(CodedIndexes.MethodDefOrRef, buf, ref position);
			value.Instantiation = Heap.ReadBlobHeapIndex(buf, ref position);
			return value;
		}

	}

}
