/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct NestedClassRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.NestedClass;

		public int Index;
		public TypeDefRowIndex NestedClass;
		public TypeDefRowIndex EnclosingClass;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct NestedClassRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal NestedClassRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator NestedClassRowIndex(RowIndex rowIndex) {
			return new NestedClassRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(NestedClassRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class NestedClassRowFactory : RowFactory<NestedClassRow> {

		public NestedClassRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return NestedClassRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ Heap.GetPhysicalSizeOfIndex(TypeDefRow.TableId)
				+ Heap.GetPhysicalSizeOfIndex(TypeDefRow.TableId)
				;
		}

		public override NestedClassRow Parse(byte[] buf, ref int position) {
			NestedClassRow value;
			value.Index = 0;
			value.NestedClass = (TypeDefRowIndex)Heap.ReadRowIndex(TypeDefRow.TableId, buf, ref position);
			value.EnclosingClass = (TypeDefRowIndex)Heap.ReadRowIndex(TypeDefRow.TableId, buf, ref position);
			return value;
		}

	}

}
