/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct PropertyRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.Property;

		public int Index;
		public PropertyAttributes Flags;
		public StringHeapIndex Name;
		public BlobHeapIndex Type;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct PropertyRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal PropertyRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator PropertyRowIndex(RowIndex rowIndex) {
			return new PropertyRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(PropertyRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class PropertyRowFactory : RowFactory<PropertyRow> {

		public PropertyRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return PropertyRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ 2
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.String)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.Blob)
				;
		}

		public override PropertyRow Parse(byte[] buf, ref int position) {
			PropertyRow value;
			value.Index = 0;
			value.Flags = (PropertyAttributes)Heap.ReadEnum16(buf, ref position);
			value.Name = Heap.ReadStringHeapIndex(buf, ref position);
			value.Type = Heap.ReadBlobHeapIndex(buf, ref position);
			return value;
		}

	}

}
