/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct StandAloneSigRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.StandAloneSig;

		public int Index;
		public BlobHeapIndex Signature;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct StandAloneSigRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal StandAloneSigRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator StandAloneSigRowIndex(RowIndex rowIndex) {
			return new StandAloneSigRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(StandAloneSigRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class StandAloneSigRowFactory : RowFactory<StandAloneSigRow> {

		public StandAloneSigRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return StandAloneSigRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.Blob)
				;
		}

		public override StandAloneSigRow Parse(byte[] buf, ref int position) {
			StandAloneSigRow value;
			value.Index = 0;
			value.Signature = Heap.ReadBlobHeapIndex(buf, ref position);
			return value;
		}

	}

}
