/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct TypeRefRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.TypeRef;

		public int Index;
		public ResolutionScopeCodedIndex ResolutionScope;
		public StringHeapIndex TypeName;
		public StringHeapIndex TypeNamespace;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct TypeRefRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal TypeRefRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator TypeRefRowIndex(RowIndex rowIndex) {
			return new TypeRefRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(TypeRefRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class TypeRefRowFactory : RowFactory<TypeRefRow> {

		public TypeRefRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return TypeRefRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ Heap.GetPhysicalSizeOfIndex(CodedIndexes.ResolutionScope)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.String)
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.String)
				;
		}

		public override TypeRefRow Parse(byte[] buf, ref int position) {
			TypeRefRow value;
			value.Index = 0;
			value.ResolutionScope = (ResolutionScopeCodedIndex)Heap.ReadCodedIndex(CodedIndexes.ResolutionScope, buf, ref position);
			value.TypeName = Heap.ReadStringHeapIndex(buf, ref position);
			value.TypeNamespace = Heap.ReadStringHeapIndex(buf, ref position);
			return value;
		}

	}

}
