/* This file is automatically generated by cliutil.exe */
using System;
using CooS.Formats.CLI.Metadata.Heaps;
using CooS.Formats.CLI.Metadata.Indexes;

namespace CooS.Formats.CLI.Metadata.Rows {

	public struct TypeSpecRow : IRow {

		public const TableId TableId = CooS.Formats.CLI.Metadata.TableId.TypeSpec;

		public int Index;
		public BlobHeapIndex Signature;

		public int RowIndex {
			get {
				return this.Index;
			}
			set {
				this.Index = value;
			}
		}

	}

	public struct TypeSpecRowIndex : IRowIndex {

		public readonly int Value;

		int IRowIndex.RawIndex {
			get {
				return this.Value;
			}
		}

		internal TypeSpecRowIndex(int value) {
			this.Value = value;
		}

		public static explicit operator TypeSpecRowIndex(RowIndex rowIndex) {
			return new TypeSpecRowIndex(rowIndex.Value);
		}

		public static implicit operator RowIndex(TypeSpecRowIndex rowIndex) {
			return new RowIndex(rowIndex.Value);
		}

	}

	internal class TypeSpecRowFactory : RowFactory<TypeSpecRow> {

		public TypeSpecRowFactory(TablesHeap heap) : base(heap) {
		}

		public override TableId TableId { get { return TypeSpecRow.TableId; } }

		public override int GetPhysicalSize() {
			return 0
				+ Heap.GetPhysicalSizeOfIndex(HeapIndexes.Blob)
				;
		}

		public override TypeSpecRow Parse(byte[] buf, ref int position) {
			TypeSpecRow value;
			value.Index = 0;
			value.Signature = Heap.ReadBlobHeapIndex(buf, ref position);
			return value;
		}

	}

}
