/* This file is automatically generated by cliutil.exe */
using System;

namespace CooS.Formats.CLI.Metadata {

	public enum CodedIndexes {
		TypeDefOrRef,
		HasConstant,
		HasCustomAttribute,
		HasFieldMarshal,
		HasDeclSecurity,
		MemberRefParent,
		HasSemantics,
		MethodDefOrRef,
		MemberForwarded,
		Implementation,
		CustomAttributeType,
		ResolutionScope,
		TypeOrMethodDef,
	}

}
