// This file is automatically generated by fdev.exe.
// Don't edit this file manually.

using System;

namespace CooS.Execution {

public partial class FieldInfo {

	public CooS.Reflection.TypeBase Type {
		get { return this.Base.Type; }
	}

	public String Name {
		get { return this.Base.Name; }
	}

	public String FullName {
		get { return this.Base.FullName; }
	}

	public CooS.Reflection.TypeBase ReturnType {
		get { return this.Base.ReturnType; }
	}

	public Boolean IsStatic {
		get { return this.Base.IsStatic; }
	}

	}

}
