// This file is automatically generated by fdev.exe.
// Don't edit this file manually.

using System;

namespace CooS.Execution {

public partial class MethodInfo {

	public CooS.Reflection.AssemblyBase Assembly {
		get { return this.Base.Assembly; }
	}

	public CooS.Reflection.TypeBase Type {
		get { return this.Base.Type; }
	}

	public String Name {
		get { return this.Base.Name; }
	}

	public Int32 Id {
		get { return this.Base.Id; }
	}

	public String FullName {
		get { return this.Base.FullName; }
	}

	public Boolean IsStatic {
		get { return this.Base.IsStatic; }
	}

	public Boolean IsGenericMethod {
		get { return this.Base.IsGenericMethod; }
	}

	public Boolean IsConstructor {
		get { return this.Base.IsConstructor; }
	}

	public Boolean IsBlank {
		get { return this.Base.IsBlank; }
	}

	public Boolean IsVirtual {
		get { return this.Base.IsVirtual; }
	}

	public CooS.Reflection.TypeBase ReturnType {
		get { return this.Base.ReturnType; }
	}

	public Boolean HasReturnValue {
		get { return this.Base.HasReturnValue; }
	}

	public Int32 ParameterCount {
		get { return this.Base.ParameterCount; }
	}

	public Int32 ArgumentCount {
		get { return this.Base.ArgumentCount; }
	}

	public Int32 VariableCount {
		get { return this.Base.VariableCount; }
	}

	public CooS.Reflection.TypeBase GetParameterType(System.Int32 index)
	{ return this.Base.GetParameterType(index); }

	public CooS.Reflection.TypeBase GetArgumentType(System.Int32 index)
	{ return this.Base.GetArgumentType(index); }

	public CooS.Reflection.TypeBase GetVariableType(System.Int32 index)
	{ return this.Base.GetVariableType(index); }

	}

}
